import { certificateImage, printCertificate } from "./certificateImage";
import React,{useEffect,useState} from 'react';
import {SaaSApp} from '../types';
type Lecture={id:string;title:string;duration:string;freePreview?:boolean};
type Certificate={id:string;issuedAt:string;name:string};
interface Props {course:SaaSApp;allLectures:Lecture[];completedLectures:Record<string,boolean>;onToggleAllLectures:(complete:boolean)=>void;onToggleLecture:(id:string,complete:boolean)=>void;}
export function CourseCertification({course,allLectures,completedLectures}:Props){
  const [certificate,setCertificate]=useState<Certificate|null>(null),[failedAt,setFailedAt]=useState<number|undefined>(),[answers,setAnswers]=useState<Record<number,number>>({}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[taking,setTaking]=useState(false);
  const questions: {question:string;options:string[]}[]=JSON.parse(course.exam||'[]');
  const complete=allLectures.length>0&&allLectures.every(l=>completedLectures[l.id]);
  useEffect(()=>{let active=true;fetch('/api/student/courses/'+course.id).then(async r=>{if(!r.ok)throw Error('Cannot load certificate status.');return r.json();}).then(d=>{if(active){setCertificate(d.state.certificate||null);setFailedAt(d.state.failedAt);}}).catch(e=>active&&setError(e.message));return()=>{active=false};},[course.id]);
  async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/exam/attempt',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({appId:course.id,answers:questions.map((_,i)=>answers[i])})});const d=await r.json();if(!r.ok)throw Error(d.error);setFailedAt(d.failedAt);setCertificate(d.certificate||null);setTaking(false);if(!d.passed)setError(`Your score was ${d.score}. Review the course and try again after 48 hours.`);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  function download(){if(!certificate)return;const text=`VISION79 DIGITAL\nCertificate of completion\n\n${certificate.name}\n${course.name}\nIssued: ${new Date(certificate.issuedAt).toLocaleDateString()}\nCertificate: ${certificate.id}\nVerify: ${location.origin}/api/certificates/${certificate.id}\n`;const url=URL.createObjectURL(new Blob([text],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download=certificate.id+'.txt';a.click();URL.revokeObjectURL(url);}
  function imageAction(print=false){if(!certificate)return;try{const canvas=certificateImage(certificate.name,course.name,certificate.id,certificate.issuedAt);if(print){printCertificate(canvas);return;}const a=document.createElement('a');a.href=canvas.toDataURL('image/png');a.download=certificate.id+'.png';a.click();}catch(e){setError((e as Error).message);}}
  return <section className="space-y-4"><h3 className="font-bold text-lg">Assessment and certificate</h3>{error&&<p role="alert" className="text-red-500">{error}</p>}{certificate?<div className="border border-teal-500 rounded-xl p-5 space-y-3"><p className="font-bold text-teal-500">Course completed</p><p>{certificate.name}</p><p>{course.name}</p><p className="text-sm break-all">{certificate.id}</p><p>Issued {new Date(certificate.issuedAt).toLocaleDateString()}</p><a className="underline" href={'/api/certificates/'+certificate.id} target="_blank" rel="noreferrer">Verify certificate</a><div className="flex gap-4"><button onClick={download}>Download record</button><button onClick={()=>imageAction()}>Download certificate PNG</button><button onClick={()=>imageAction(true)}>Print certificate</button></div></div>:taking?<form onSubmit={submit} className="space-y-5">{questions.map((q,i)=><fieldset key={i}><legend className="font-semibold">{i+1}. {q.question}</legend>{q.options.map((o,j)=><label className="flex gap-2 p-2" key={j}><input required type="radio" name={'question-'+i} checked={answers[i]===j} onChange={()=>setAnswers(p=>({...p,[i]:j}))}/>{o}</label>)}</fieldset>)}<button disabled={busy} className="p-3 rounded bg-teal-700 text-white">{busy?'Submitting…':'Submit assessment'}</button><button type="button" onClick={()=>setTaking(false)} className="ml-3">Cancel</button></form>:<><p>Complete every lecture, then answer all assessment questions correctly. Failed attempts have a 48-hour review period.</p>{failedAt&&Date.now()-failedAt<48*3600000?<p>Next attempt: {new Date(failedAt+48*3600000).toLocaleString()}</p>:<button disabled={!complete||!questions.length} onClick={()=>setTaking(true)} className="p-3 rounded bg-teal-700 text-white disabled:opacity-50">{complete?'Start assessment':'Complete the lectures first'}</button>}</>}</section>;
}
