import React, {useEffect, useState} from 'react';
export type Learner = {id:string;name:string;email:string};
export function LearnerAccess({children}:{children:(user:Learner)=>React.ReactNode}) {
  const [user,setUser]=useState<Learner|null>(null),[loading,setLoading]=useState(true),[mode,setMode]=useState('login'),[error,setError]=useState(''),[recovery,setRecovery]=useState(''),[busy,setBusy]=useState(false);
  async function refresh(){const res=await fetch('/api/student/me');setUser(res.ok?await res.json():null);}
  useEffect(()=>{refresh().catch(()=>setError('Cannot connect. Please retry.')).finally(()=>setLoading(false));},[]);
  async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const data=Object.fromEntries(new FormData(e.currentTarget));try{const res=await fetch('/api/student/'+mode,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const body=await res.json();if(!res.ok)throw Error(body.error);if(body.recoveryCode)setRecovery(body.recoveryCode);await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  if(loading)return <p role="status">Loading your learner account…</p>;
  if(recovery)return <section className="p-6 rounded-xl border border-app-border space-y-4"><h2 className="text-xl font-bold">Save your recovery code</h2><p>This code lets you regain access if you forget your password. Keep it somewhere private. It is shown only once.</p><code className="block break-all select-all">{recovery}</code><button className="p-3 bg-teal-700 text-white rounded" onClick={()=>setRecovery('')}>I have saved my code — continue</button></section>;
  if(user)return <><div className="flex flex-wrap justify-between gap-3 mb-4"><span>Signed in as {user.name}</span><button onClick={async()=>{try{const r=await fetch('/api/student/logout',{method:'POST'});if(!r.ok)throw Error();setUser(null);}catch{setError('Could not sign out. Please retry.');}}}>Sign out</button>{error&&<p role="alert">{error}</p>}</div>{children(user)}</>;
  return <section className="max-w-lg mx-auto p-6 rounded-xl border border-app-border space-y-4"><h2 className="text-2xl font-bold">Your learning account</h2><p>Keep enrollment, progress, notes and certificates together across your devices.</p><div className="flex gap-4">{[['login','Sign in'],['register','Create account'],['recover','Recover access']].map(([value,label])=><button key={value} onClick={()=>{setMode(value);setError('');}} aria-pressed={mode===value}>{label}</button>)}</div><form onSubmit={submit} className="space-y-4">{mode==='register'&&<label className="block">Full name<input className="block w-full p-3 bg-app-input border rounded" name="name" autoComplete="name" required maxLength={100}/></label>}<label className="block">Email<input className="block w-full p-3 bg-app-input border rounded" type="email" name="email" autoComplete="email" required maxLength={254}/></label>{mode==='recover'&&<label className="block">Recovery code<input className="block w-full p-3 bg-app-input border rounded" name="recoveryCode" required/></label>}<label className="block">{mode==='recover'?'New password':'Password'}<input className="block w-full p-3 bg-app-input border rounded" name="password" type="password" autoComplete={mode==='login'?'current-password':'new-password'} required minLength={mode==='login'?1:12} maxLength={256}/></label><p className="text-sm">New passwords must have at least 12 characters.</p>{error&&<p role="alert">{error}</p>}<button disabled={busy} className="p-3 bg-teal-700 text-white rounded">{busy?'Please wait…':mode==='login'?'Sign in':mode==='register'?'Create account':'Recover account'}</button></form></section>;
}
